Repository flower-project-2024/WHOA_Server, pull requests merged in 2024-05, with the labels that each got.

#55 [Fix] Flower Entity 수정
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
Labels: Fix

#56 [Fix] Flower 엔티티 수정
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommandResponseDto.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
Labels: Fix

#61 Feat: 꽃 이미지 등록 API
  src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommendResponseDto.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerRequestDto.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
  src/main/java/com/whoa/whoaserver/flower/service/S3Uploader.java
Labels: Feature

#62 Feat: 꽃 이미지 등록 API
  src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerRecommendResponseDto.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerRequestDto.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
  src/main/java/com/whoa/whoaserver/flower/service/S3Uploader.java
Labels: Feature

#76 [Fix] POST 등록 시 bouquetName 예외 처리 정교화
  src/main/java/com/whoa/whoaserver/bouquet/repository/BouquetRepository.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
Labels: Fix

#78 [Fix] @ExceptionHandler 400 bad request response parameter && request DTO null mapping
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingController.java
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
  src/main/java/com/whoa/whoaserver/global/exception/GlobalExceptionHandler.java
Labels: Bug/Error, Fix

#80 [Feat] POST 및 GET 요청 시 substitutionType 추가
  src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/type/flowerSubstitutionTypeOption.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/BouquetCustomizingRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
Labels: Feature

#83 [Feat] 한 번의 API 호출로 여러 이미지 동시 업로드 구현
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/MultipartFileUploadRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/MultipartFileUploadedUrlResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
  src/main/java/com/whoa/whoaserver/global/config/S3Config.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
Labels: Feature

#85 [Refact] stream 불변성 보장하도록 수정
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
  src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
Labels: Refactor

#87 [Fix] 키워드 별 꽃 조회 매핑 테이블 기반 로직 수정 완료
  src/main/java/com/whoa/whoaserver/keyword/dto/response/FlowerInfoByKeywordResponse.java
  src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
  src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepository.java
Labels: Fix, Feature
