Repository flower-project-2024/WHOA_Server, pull requests merged in 2024-06, with the labels that each got.

#90 [CI/CD] Docker(compose) + 블루그린 무중단 배포 최종 완료
  .github/workflows/main.yml
  nginx/conf.d/nginx.conf
Labels: Infra Setting

#92 [Feat] 키워드 별 꽃 조회 꽃말에 따른 서로 다른 이미지 반환 및 발화 시기 고려
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
  src/main/java/com/whoa/whoaserver/flower/repository/FlowerImageRepository.java
  src/main/java/com/whoa/whoaserver/flower/utils/FlowerUtils.java
  src/main/java/com/whoa/whoaserver/flowerExpression/domain/FlowerExpression.java
  src/main/java/com/whoa/whoaserver/keyword/dto/response/FlowerInfoByKeywordResponse.java
  src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
Labels: Feature

#93 [Feat] bouquet 단건 상세 조회 키워드에서 꽃말 반환으로 변경
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
  src/main/java/com/whoa/whoaserver/flowerExpression/repository/FlowerExpressionRepository.java
  src/main/java/com/whoa/whoaserver/keyword/dto/response/FlowerInfoByKeywordResponse.java
Labels: Feature

#94 [Fix] 다중 이미지 업로드 최종 완료
  build.gradle
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
  src/main/java/com/whoa/whoaserver/global/config/S3Config.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
Labels: Bug/Error, Feature

#100 [Refact] 키워드별 꽃 조회 Querydsl 적용
  build.gradle
  src/main/java/com/whoa/whoaserver/global/config/QuerydslConfig.java
  src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
  src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepository.java
  src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepositoryCustom.java
  src/main/java/com/whoa/whoaserver/mapping/repository/FlowerExpressionKeywordRepositoryImpl.java
Labels: Refactor

#102 [Fix] 저렴한꽃/오늘의꽃 API 수정
  src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
  src/test/java/com/whoa/whoaserver/FlowerCrawlerSchedulerTest.java
Labels: Fix

#103 [Fix] 오늘의꽃/저렴한꽃 API 수정
  src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
  src/test/java/com/whoa/whoaserver/FlowerCrawlerSchedulerTest.java
Labels: Fix

#106 [Fix] 오늘의꽃/저렴한꽃 API 수정
  src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
Labels: Fix

#107 [Fix] 오늘의꽃/저렴한꽃 API 수정
  src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
Labels: Fix
