Repository flower-project-2024/WHOA_Server, pull requests merged in 2024-03, with the labels that each got.

#21 [Feat] 꽃다발 커스터마이징 CRUD 전체 API
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetCustomizingController.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetRepository.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/BouquetCustomizingRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetCustomizingResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetOrderResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
  src/test/java/com/whoa/whoaserver/bouquet/domain/BouquetTest.java
Labels: Feature

#26 [Feat] 꽃 검색을 위한 API
  src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerSearchResponseDto.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
Labels: Feature

#27 [Feat, Refact] AWS presignedUrl 발급 로직 추가 및 수정
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/PresignedUrlRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
Labels: Feature, Refactor

#30 [Refact] 멤버 등록 API 리팩토링
  src/main/java/com/whoa/whoaserver/member/domain/Member.java
  src/main/java/com/whoa/whoaserver/member/service/MemberService.java
Labels: Refactor

#24 Feat: 저렴한 꽃 조회 API
  .gitignore
  build.gradle
  src/main/java/com/whoa/whoaserver/crawl/controller/FlowerRankingController.java
  src/main/java/com/whoa/whoaserver/crawl/domain/FlowerRanking.java
  src/main/java/com/whoa/whoaserver/crawl/dto/FlowerRankingResponseDto.java
  src/main/java/com/whoa/whoaserver/crawl/repository/FlowerRankingRepository.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerCrawlerScheduler.java
  src/main/java/com/whoa/whoaserver/crawl/service/FlowerRankingService.java
  src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
  src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
  src/main/resources/application.yml
  src/test/java/com/whoa/whoaserver/FlowerCrawlerSchedulerTest.java
Labels: Feature

#33 [Refact] 공통 Response 및 전역 예외 처리
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
  src/main/java/com/whoa/whoaserver/global/dto/common/CommonResponse.java
  src/main/java/com/whoa/whoaserver/global/dto/common/CommonResponseAdvice.java
  src/main/java/com/whoa/whoaserver/global/exception/BadRequestException.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionResponse.java
  src/main/java/com/whoa/whoaserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/whoa/whoaserver/global/exception/WhoaException.java
  src/main/java/com/whoa/whoaserver/member/service/MemberService.java
Labels: Feature, Refactor

#38 [Feat] 키워드별 꽃 조회에서 키워드 전체에 해당하는 꽃 조회 기능 추가
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
  src/main/java/com/whoa/whoaserver/keyword/service/FlowerKeywordService.java
Labels: Feature

#39 [Refact] 이미지 파일명 중복 예외 처리 및 이미지 반환 로직 수정
  src/main/java/com/whoa/whoaserver/bouquet/domain/Bouquet.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetImage.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetRepository.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/BouquetCustomizingRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/PresignedUrlRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetCustomizingResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetInfoDetailResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/BouquetOrderResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetCustomizingService.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
Labels: Feature, Refactor
