Repository flower-project-2024/WHOA_Server, pull requests merged in 2024-02, with the labels that each got.

#3 [Infra] Basic setting
  .gitignore
  build.gradle
  src/main/java/com/whoa/whoaserver/flower/service/S3Uploader.java
  src/main/java/com/whoa/whoaserver/global/config/S3Config.java
  src/main/java/com/whoa/whoaserver/global/config/SwaggerConfig.java
  src/main/java/com/whoa/whoaserver/global/exception/BadRequestException.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionResponse.java
  src/main/java/com/whoa/whoaserver/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: Infra Setting

#5 [Feat] 멤버 등록
  src/main/java/com/whoa/whoaserver/TempController.java
  src/main/java/com/whoa/whoaserver/member/controller/MemberController.java
  src/main/java/com/whoa/whoaserver/member/domain/Member.java
  src/main/java/com/whoa/whoaserver/member/domain/MemberRepository.java
  src/main/java/com/whoa/whoaserver/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/whoa/whoaserver/member/dto/response/MemberInfo.java
  src/main/java/com/whoa/whoaserver/member/service/MemberService.java
Labels: Feature

#7 Feat: 꽃 조회 API 개발
  .gitignore
  src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/flower/dto/FlowerResponseDto.java
  src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
  src/main/java/com/whoa/whoaserver/flowerExpression/domain/FlowerExpression.java
  src/main/java/com/whoa/whoaserver/flowerExpression/dto/FlowerExpressionResponseDto.java
  src/main/java/com/whoa/whoaserver/keyword/domain/Keyword.java
Labels: Feature

#10 Feat: @DeviceUser 정의하여 유저 정보 기반의 기능 세팅 및 S3 presigned URL 발급 구현 완료
  .gitignore
  build.gradle
  src/main/java/com/whoa/whoaserver/TempController.java
  src/main/java/com/whoa/whoaserver/bouquet/controller/BouquetImageController.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetImage.java
  src/main/java/com/whoa/whoaserver/bouquet/domain/BouquetImageRepository.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/request/PresignedUrlRequest.java
  src/main/java/com/whoa/whoaserver/bouquet/dto/response/PresignedUrlResponse.java
  src/main/java/com/whoa/whoaserver/bouquet/service/BouquetImageService.java
  src/main/java/com/whoa/whoaserver/global/annotation/DeviceUser.java
  src/main/java/com/whoa/whoaserver/global/config/S3Config.java
  src/main/java/com/whoa/whoaserver/global/config/WebConfig.java
  src/main/java/com/whoa/whoaserver/global/dto/UserContext.java
  src/main/java/com/whoa/whoaserver/global/exception/ExceptionCode.java
  src/main/java/com/whoa/whoaserver/global/extension/Extension.java
  src/main/java/com/whoa/whoaserver/global/properties/S3Properties.java
  src/main/java/com/whoa/whoaserver/global/resolver/DeviceUserArgumentResolver.java
  src/main/java/com/whoa/whoaserver/member/controller/MemberController.java
  src/main/java/com/whoa/whoaserver/member/domain/Member.java
  src/main/java/com/whoa/whoaserver/member/domain/MemberRepository.java
  src/main/java/com/whoa/whoaserver/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/whoa/whoaserver/member/dto/response/MemberInfo.java
  src/main/java/com/whoa/whoaserver/member/service/MemberService.java
  src/main/resources/application.yml
Labels: Feature

#14 [Fix] Keyword, Flower 매핑
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/keyword/domain/Keyword.java
Labels: Fix

#12 [Feat] 오늘의꽃 조회 API
  src/main/java/com/whoa/whoaserver/flower/controller/FlowerController.java
  src/main/java/com/whoa/whoaserver/flower/domain/Flower.java
  src/main/java/com/whoa/whoaserver/flower/repository/FlowerRepository.java
  src/main/java/com/whoa/whoaserver/flower/service/FlowerService.java
Labels: Feature
